@startuml

interface IPlataforma{
 +EnviarMensaje(String)
}

class Notificacion {
-plataforma:IPlataforma,
+Alerta(String),
+Advertencia(String),
+Mensaje(String),
+Confirmacion(String)
}

class PlataformaEscritorio {
 +EnviarMensaje(String)
 }

class PlataformaMovil {
 +EnviarMensaje(String)
 }
 
 class PlataformaWeb {
  +EnviarMensaje(String)
 }
 
PlataformaEscritorio ..|> IPlataforma
PlataformaMovil --|>  IPlataforma
PlataformaWeb --|> IPlataforma
Notificacion *--> IPlataforma
@enduml